version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipenv.lock" }}

      - run:
          name: install dependencies
          command: |
            pipenv install --dev

      - save_cache:
          paths:
            - ~/.local/share/virtualenvs
          key: v1-dependencies-{{ checksum "Pipenv.lock" }}

      - run:
          name: run tests
          command: |
            pipenv run nosetests
